const ATUALIZAR_EMAIL_PUT_REQUEST = 'ATUALIZAR_EMAIL_PUT_REQUEST';
const ATUALIZAR_EMAIL_PUT_RESPONSE = 'ATUALIZAR_EMAIL_PUT_RESPONSE';
const ATUALIZAR_EMAIL_PUT_FAILURE = 'ATUALIZAR_EMAIL_PUT_FAILURE';

const ATUALIZAR_TOKEN_GET_REQUEST = 'ATUALIZAR_TOKEN_GET_REQUEST';
const ATUALIZAR_TOKEN_GET_RESPONSE = 'ATUALIZAR_TOKEN_GET_RESPONSE';
const ATUALIZAR_TOKEN_GET_FAILURE = 'ATUALIZAR_TOKEN_GET_FAILURE';

const DELETAR_USUARIO_DELETE_REQUEST = 'DELETAR_USUARIO_DELETE_REQUEST';
const DELETAR_USUARIO_DELETE_RESPONSE = 'DELETAR_USUARIO_DELETE_RESPONSE';
const DELETAR_USUARIO_DELETE_FAILURE = 'DELETAR_USUARIO_DELETE_FAILURE';

const DELETAR_USUARIO_SEM_RETORNO_DELETE_REQUEST = 'DELETAR_USUARIO_SEM_RETORNO_DELETE_REQUEST';
const DELETAR_USUARIO_SEM_RETORNO_DELETE_RESPONSE = 'DELETAR_USUARIO_SEM_RETORNO_DELETE_RESPONSE';
const DELETAR_USUARIO_SEM_RETORNO_DELETE_FAILURE = 'DELETAR_USUARIO_SEM_RETORNO_DELETE_FAILURE';

const INSERIR_USUARIO_POST_REQUEST = 'INSERIR_USUARIO_POST_REQUEST';
const INSERIR_USUARIO_POST_RESPONSE = 'INSERIR_USUARIO_POST_RESPONSE';
const INSERIR_USUARIO_POST_FAILURE = 'INSERIR_USUARIO_POST_FAILURE';

const LISTAR_DADOS_POR_TOKEN_POST_REQUEST = 'LISTAR_DADOS_POR_TOKEN_POST_REQUEST';
const LISTAR_DADOS_POR_TOKEN_POST_RESPONSE = 'LISTAR_DADOS_POR_TOKEN_POST_RESPONSE';
const LISTAR_DADOS_POR_TOKEN_POST_FAILURE = 'LISTAR_DADOS_POR_TOKEN_POST_FAILURE';

const LISTAR_USUARIOS_DELETE_REQUEST = 'LISTAR_USUARIOS_DELETE_REQUEST';
const LISTAR_USUARIOS_DELETE_RESPONSE = 'LISTAR_USUARIOS_DELETE_RESPONSE';
const LISTAR_USUARIOS_DELETE_FAILURE = 'LISTAR_USUARIOS_DELETE_FAILURE';

const METODO_GET_PARAMETROS_PESQUISA_GET_REQUEST = 'METODO_GET_PARAMETROS_PESQUISA_GET_REQUEST';
const METODO_GET_PARAMETROS_PESQUISA_GET_RESPONSE = 'METODO_GET_PARAMETROS_PESQUISA_GET_RESPONSE';
const METODO_GET_PARAMETROS_PESQUISA_GET_FAILURE = 'METODO_GET_PARAMETROS_PESQUISA_GET_FAILURE';

const METODO_TESTE_APRESENTACAO_GET_REQUEST = 'METODO_TESTE_APRESENTACAO_GET_REQUEST';
const METODO_TESTE_APRESENTACAO_GET_RESPONSE = 'METODO_TESTE_APRESENTACAO_GET_RESPONSE';
const METODO_TESTE_APRESENTACAO_GET_FAILURE = 'METODO_TESTE_APRESENTACAO_GET_FAILURE';

const OBTER_DICIONARIO_GET_REQUEST = 'OBTER_DICIONARIO_GET_REQUEST';
const OBTER_DICIONARIO_GET_RESPONSE = 'OBTER_DICIONARIO_GET_RESPONSE';
const OBTER_DICIONARIO_GET_FAILURE = 'OBTER_DICIONARIO_GET_FAILURE';

const OBTER_LISTA_NUMEROS_PUT_REQUEST = 'OBTER_LISTA_NUMEROS_PUT_REQUEST';
const OBTER_LISTA_NUMEROS_PUT_RESPONSE = 'OBTER_LISTA_NUMEROS_PUT_RESPONSE';
const OBTER_LISTA_NUMEROS_PUT_FAILURE = 'OBTER_LISTA_NUMEROS_PUT_FAILURE';

const atualizarEmailPutActionsTypes = [
  ATUALIZAR_EMAIL_PUT_REQUEST,
  ATUALIZAR_EMAIL_PUT_RESPONSE,
  ATUALIZAR_EMAIL_PUT_FAILURE,
];

const atualizarTokenGetActionsTypes = [
  ATUALIZAR_TOKEN_GET_REQUEST,
  ATUALIZAR_TOKEN_GET_RESPONSE,
  ATUALIZAR_TOKEN_GET_FAILURE,
];

const deletarUsuarioDeleteActionsTypes = [
  DELETAR_USUARIO_DELETE_REQUEST,
  DELETAR_USUARIO_DELETE_RESPONSE,
  DELETAR_USUARIO_DELETE_FAILURE,
];

const deletarUsuarioSemRetornoDeleteActionsTypes = [
  DELETAR_USUARIO_SEM_RETORNO_DELETE_REQUEST,
  DELETAR_USUARIO_SEM_RETORNO_DELETE_RESPONSE,
  DELETAR_USUARIO_SEM_RETORNO_DELETE_FAILURE,
];

const inserirUsuarioPostActionsTypes = [
  INSERIR_USUARIO_POST_REQUEST,
  INSERIR_USUARIO_POST_RESPONSE,
  INSERIR_USUARIO_POST_FAILURE,
];

const listarDadosPorTokenPostActionsTypes = [
  LISTAR_DADOS_POR_TOKEN_POST_REQUEST,
  LISTAR_DADOS_POR_TOKEN_POST_RESPONSE,
  LISTAR_DADOS_POR_TOKEN_POST_FAILURE,
];

const listarUsuariosDeleteActionsTypes = [
  LISTAR_USUARIOS_DELETE_REQUEST,
  LISTAR_USUARIOS_DELETE_RESPONSE,
  LISTAR_USUARIOS_DELETE_FAILURE,
];

const metodoGetParametrosPesquisaGetActionsTypes = [
  METODO_GET_PARAMETROS_PESQUISA_GET_REQUEST,
  METODO_GET_PARAMETROS_PESQUISA_GET_RESPONSE,
  METODO_GET_PARAMETROS_PESQUISA_GET_FAILURE,
];

const metodoTesteApresentacaoGetActionsTypes = [
  METODO_TESTE_APRESENTACAO_GET_REQUEST,
  METODO_TESTE_APRESENTACAO_GET_RESPONSE,
  METODO_TESTE_APRESENTACAO_GET_FAILURE,
];

const obterDicionarioGetActionsTypes = [
  OBTER_DICIONARIO_GET_REQUEST,
  OBTER_DICIONARIO_GET_RESPONSE,
  OBTER_DICIONARIO_GET_FAILURE,
];

const obterListaNumerosPutActionsTypes = [
  OBTER_LISTA_NUMEROS_PUT_REQUEST,
  OBTER_LISTA_NUMEROS_PUT_RESPONSE,
  OBTER_LISTA_NUMEROS_PUT_FAILURE,
];


export const ActionsTypes =  {
  ATUALIZAR_EMAIL_PUT_REQUEST,
  ATUALIZAR_EMAIL_PUT_RESPONSE,
  ATUALIZAR_EMAIL_PUT_FAILURE,
  atualizarEmailPutActionsTypes,
  ATUALIZAR_TOKEN_GET_REQUEST,
  ATUALIZAR_TOKEN_GET_RESPONSE,
  ATUALIZAR_TOKEN_GET_FAILURE,
  atualizarTokenGetActionsTypes,
  DELETAR_USUARIO_DELETE_REQUEST,
  DELETAR_USUARIO_DELETE_RESPONSE,
  DELETAR_USUARIO_DELETE_FAILURE,
  deletarUsuarioDeleteActionsTypes,
  DELETAR_USUARIO_SEM_RETORNO_DELETE_REQUEST,
  DELETAR_USUARIO_SEM_RETORNO_DELETE_RESPONSE,
  DELETAR_USUARIO_SEM_RETORNO_DELETE_FAILURE,
  deletarUsuarioSemRetornoDeleteActionsTypes,
  INSERIR_USUARIO_POST_REQUEST,
  INSERIR_USUARIO_POST_RESPONSE,
  INSERIR_USUARIO_POST_FAILURE,
  inserirUsuarioPostActionsTypes,
  LISTAR_DADOS_POR_TOKEN_POST_REQUEST,
  LISTAR_DADOS_POR_TOKEN_POST_RESPONSE,
  LISTAR_DADOS_POR_TOKEN_POST_FAILURE,
  listarDadosPorTokenPostActionsTypes,
  LISTAR_USUARIOS_DELETE_REQUEST,
  LISTAR_USUARIOS_DELETE_RESPONSE,
  LISTAR_USUARIOS_DELETE_FAILURE,
  listarUsuariosDeleteActionsTypes,
  METODO_GET_PARAMETROS_PESQUISA_GET_REQUEST,
  METODO_GET_PARAMETROS_PESQUISA_GET_RESPONSE,
  METODO_GET_PARAMETROS_PESQUISA_GET_FAILURE,
  metodoGetParametrosPesquisaGetActionsTypes,
  METODO_TESTE_APRESENTACAO_GET_REQUEST,
  METODO_TESTE_APRESENTACAO_GET_RESPONSE,
  METODO_TESTE_APRESENTACAO_GET_FAILURE,
  metodoTesteApresentacaoGetActionsTypes,
  OBTER_DICIONARIO_GET_REQUEST,
  OBTER_DICIONARIO_GET_RESPONSE,
  OBTER_DICIONARIO_GET_FAILURE,
  obterDicionarioGetActionsTypes,
  OBTER_LISTA_NUMEROS_PUT_REQUEST,
  OBTER_LISTA_NUMEROS_PUT_RESPONSE,
  OBTER_LISTA_NUMEROS_PUT_FAILURE,
  obterListaNumerosPutActionsTypes
};
