const MUNICIPIO_BY_CODIGO_DELETE_REQUEST = 'MUNICIPIO_BY_CODIGO_DELETE_REQUEST';
const MUNICIPIO_BY_CODIGO_DELETE_RESPONSE = 'MUNICIPIO_BY_CODIGO_DELETE_RESPONSE';
const MUNICIPIO_BY_CODIGO_DELETE_FAILURE = 'MUNICIPIO_BY_CODIGO_DELETE_FAILURE';

const MUNICIPIO_BY_CODIGO_GET_REQUEST = 'MUNICIPIO_BY_CODIGO_GET_REQUEST';
const MUNICIPIO_BY_CODIGO_GET_RESPONSE = 'MUNICIPIO_BY_CODIGO_GET_RESPONSE';
const MUNICIPIO_BY_CODIGO_GET_FAILURE = 'MUNICIPIO_BY_CODIGO_GET_FAILURE';

const MUNICIPIO_BY_CODIGO_PUT_REQUEST = 'MUNICIPIO_BY_CODIGO_PUT_REQUEST';
const MUNICIPIO_BY_CODIGO_PUT_RESPONSE = 'MUNICIPIO_BY_CODIGO_PUT_RESPONSE';
const MUNICIPIO_BY_CODIGO_PUT_FAILURE = 'MUNICIPIO_BY_CODIGO_PUT_FAILURE';

const MUNICIPIO_GET_REQUEST = 'MUNICIPIO_GET_REQUEST';
const MUNICIPIO_GET_RESPONSE = 'MUNICIPIO_GET_RESPONSE';
const MUNICIPIO_GET_FAILURE = 'MUNICIPIO_GET_FAILURE';

const MUNICIPIO_POST_REQUEST = 'MUNICIPIO_POST_REQUEST';
const MUNICIPIO_POST_RESPONSE = 'MUNICIPIO_POST_RESPONSE';
const MUNICIPIO_POST_FAILURE = 'MUNICIPIO_POST_FAILURE';

const municipioByCodigoDeleteActionsTypes = [
  MUNICIPIO_BY_CODIGO_DELETE_REQUEST,
  MUNICIPIO_BY_CODIGO_DELETE_RESPONSE,
  MUNICIPIO_BY_CODIGO_DELETE_FAILURE,
];

const municipioByCodigoGetActionsTypes = [
  MUNICIPIO_BY_CODIGO_GET_REQUEST,
  MUNICIPIO_BY_CODIGO_GET_RESPONSE,
  MUNICIPIO_BY_CODIGO_GET_FAILURE,
];

const municipioByCodigoPutActionsTypes = [
  MUNICIPIO_BY_CODIGO_PUT_REQUEST,
  MUNICIPIO_BY_CODIGO_PUT_RESPONSE,
  MUNICIPIO_BY_CODIGO_PUT_FAILURE,
];

const municipioGetActionsTypes = [
  MUNICIPIO_GET_REQUEST,
  MUNICIPIO_GET_RESPONSE,
  MUNICIPIO_GET_FAILURE,
];

const municipioPostActionsTypes = [
  MUNICIPIO_POST_REQUEST,
  MUNICIPIO_POST_RESPONSE,
  MUNICIPIO_POST_FAILURE,
];


export const ActionsTypes =  {
  MUNICIPIO_BY_CODIGO_DELETE_REQUEST,
  MUNICIPIO_BY_CODIGO_DELETE_RESPONSE,
  MUNICIPIO_BY_CODIGO_DELETE_FAILURE,
  municipioByCodigoDeleteActionsTypes,
  MUNICIPIO_BY_CODIGO_GET_REQUEST,
  MUNICIPIO_BY_CODIGO_GET_RESPONSE,
  MUNICIPIO_BY_CODIGO_GET_FAILURE,
  municipioByCodigoGetActionsTypes,
  MUNICIPIO_BY_CODIGO_PUT_REQUEST,
  MUNICIPIO_BY_CODIGO_PUT_RESPONSE,
  MUNICIPIO_BY_CODIGO_PUT_FAILURE,
  municipioByCodigoPutActionsTypes,
  MUNICIPIO_GET_REQUEST,
  MUNICIPIO_GET_RESPONSE,
  MUNICIPIO_GET_FAILURE,
  municipioGetActionsTypes,
  MUNICIPIO_POST_REQUEST,
  MUNICIPIO_POST_RESPONSE,
  MUNICIPIO_POST_FAILURE,
  municipioPostActionsTypes
};
